[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[window]
opacity = 0.99
decorations = "none"
blur = true

[window.padding]
x = 20
y = 20

[window.dimensions]
lines = 55
columns = 275

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
key = "_"
mods = "Control|Shift"

[keyboard.bindings.command]
program = "/home/eransa/.local/bin/alacritty_config.py"
args = [
    "--key",
    "window.opacity",
    "--decrease",
    "0.01",
]

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"

[keyboard.bindings.command]
program = "/home/eransa/.local/bin/alacritty_config.py"
args = [
    "--key",
    "window.opacity",
    "--increase",
    "0.01",
]

[colors.primary]
background = "#1F1F28"
foreground = "#d5e6e6"

[colors.selection]
text = "CellForeground"
background = "#555555"

[colors.normal]
black = "#110f18"
red = "#dba5c5"
green = "#61ffca"
yellow = "#ffca85"
blue = "#6ca9ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.cursor]
text = "0x131313"
cursor = "0x959dbd"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#6ca9ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[cursor.style]
shape = "beam"
