[flavor]
dark = "catppuccin-frappe"
light = "catppuccin-frappe"

# [icon]
# prepend_exts = [
# 	{ name = "*.rs"  , text = "" },
# 	{ name = "*.lua" , text = "", fg = "#51a0cf" },
# ]
# prepend_dirs = [
# 	{ name = "Desktop/", text = "" },
# ]

[status]
separator_open  = ""
separator_close = ""

[cmp]
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

[filetype]
rules = [
	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "#ab9cb8" },

	# Empty files
	{ mime = "inode/empty", fg = "cyan" },

	# Orphan symbolic links
	{ name = "*", is = "orphan", fg = "red" },
]

[icon]
prepend_rules = [
	{ name = "*.rs"    , text = "" },
	{ name = "Desktop/", text = "" },
	{ name = "*.lua", text = "", fg = "#51a0cf" },
]
